# We don't specify a global language both because we may use different
# languages or jdks in different jobs (some of which travis may not
# provide), and because in some cases travis language-specific
# automation either does things we don't want to do, or does them too
# early in the process, i.e. lein deps, etc.  It's still possible to
# set the "language:" explicitly for a job when that's appropriate.

language: generic

dist: xenial

aliases:
  - &run-tests |
    set -e
    mkdir -p ext/travisci/local/bin
    ext/bin/require-jdk --expire "$EZBAKE_TEST_JDK" ext/travisci/local
    export JAVA_HOME="$(pwd)/ext/travisci/local/jdk"
    export PATH="$JAVA_HOME/bin:$PATH"
    hash -r
    ext/bin/require-leiningen default ext/travisci/local
    lein test

jobs:
  include:
    - stage: ezbake tests
      env: EZBAKE_TEST_JDK=openjdk8
      script: *run-tests

    - stage: ezbake tests
      env: EZBAKE_TEST_JDK=openjdk11
      script: *run-tests

notifications:
  # release-new-new
  slack:
    rooms:
      - puppet:G7vAYkGZsWAilzGj4ZrftFF6
    on_success: change
    on_failure: always
