# We don't specify a global language both because we may use different
# languages or jdks in different jobs (some of which travis may not
# provide), and because in some cases travis language-specific
# automation either does things we don't want to do, or does them too
# early in the process, i.e. lein deps, etc.  It's still possible to
# set the "language:" explicitly for a job when that's appropriate.

language: generic

dist: xenial

# Always explicitly set sudo.  Otherwise travis' defaults may vary
# based on when the repository testing was enabled.
sudo: required

aliases:
  - &run-tests |
    set -e
    mkdir -p ext/travisci/local/bin
    ext/bin/require-jdk --expire "$EZBAKE_TEST_JDK" ext/travisci/local
    export JAVA_HOME="$(pwd)/ext/travisci/local/jdk"
    export PATH="$JAVA_HOME/bin:$PATH"
    hash -r
    ext/bin/require-leiningen default ext/travisci/local
    lein test

jobs:
  include:

    - stage: ❧ ezbake tests
      env: EZBAKE_TEST_JDK=openjdk8
      script: *run-tests

    - stage: ❧ ezbake tests
      env: EZBAKE_TEST_JDK=openjdk11
      script: *run-tests

#on_success: ext/travisci/on-success

#notifications:
#  email: false
#  slack:
#    template:
#      - "<%{compare_url}|%{commit_subject}> | %{author}"
#      - "%{repository_slug} %{branch} | <%{build_url}|#%{build_number}> %{result} in %{elapsed_time}"
#    rooms:
#      secure: IJU0YgGYbKgM7NupaOmE2BYra2mNx7+e5vAYNL+5oaRXolbHCyg0WzfFWilhMK3KEi8oIMKXR4ZzoUZLAqeOQzX7nnsLqC3wjyDHCgxtp4O+5GNKyeLN4ItoI1f2d6qyiiBPkHgVPuLhG3yyQ+wD0dMc9vSYmxfoazqe9HD/9UE=

cache:
  directories:
    - /var/cache/apt/archives
    - $HOME/.m2
    - $HOME/Library/Caches/Homebrew
    - ext/travisci/local/jdk
    - vendor/bundle/ruby
